# Run continuous integration on any rust policy change
name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  calculate-policy-matrix:
    runs-on: ubuntu-latest
    outputs:
      policy_rust_working_dirs: ${{ steps.calculate-policy-dirs.outputs.policy_rust_working_dirs }}
      policy_go_working_dirs: ${{ steps.calculate-policy-dirs.outputs.policy_go_working_dirs }}
      global_cargo_file_change: ${{ steps.calculate-policy-dirs.outputs.global_cargo_file_change }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # checkout all history to do git diff
      - name: calculate which policies need a CI job
        id: calculate-policy-dirs
        shell: bash
        run: |
          # list only changes of files in `policies/`:
          git_files="$(git diff --no-color --find-renames --find-copies --name-only origin/main ${{ github.sha }} -- policies)"

          # build policy_working_dirs:
          dir_bash_array=($(echo "$git_files" | cut -d/ -f1,2 ))
          declare -p dir_bash_array # for debug
          policy_working_dirs=$(jq --compact-output --null-input '$ARGS.positional | map(select(. != "policies/Cargo.lock" and . != "policies/Cargo.toml"))' --args -- "${dir_bash_array[@]}")
          # flag with policies/Cargo.* file change
          global_cargo_file_change=false
          if [[ "$git_files" == *"policies/Cargo.toml"* || "$git_files" == *"policies/Cargo.lock"* ]]; then
              global_cargo_file_change=true
          fi
          # echo "policy_working_dirs=$policy_working_dirs" >> $GITHUB_OUTPUT
          policy_rust_working_dirs=()
          policy_go_working_dirs=()
          for policy in $(echo "$policy_working_dirs" | jq -r '.[]'); do
              # check if policy directory has cargo.toml file
              if [ -f "$policy/Cargo.toml" ]; then
                  policy_rust_working_dirs+=("$policy")
              else
                  policy_go_working_dirs+=("$policy")
              fi
          done
          policy_rust_working_dirs=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${policy_rust_working_dirs[@]}")
          policy_go_working_dirs=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${policy_go_working_dirs[@]}")
          echo "policy_rust_working_dirs=$policy_rust_working_dirs"
          echo "policy_go_working_dirs=$policy_go_working_dirs"
          echo "policy_rust_working_dirs=$policy_rust_working_dirs" >> $GITHUB_OUTPUT
          echo "policy_go_working_dirs=$policy_go_working_dirs" >> $GITHUB_OUTPUT
          echo "global_cargo_file_change=$global_cargo_file_change" >> $GITHUB_OUTPUT

  rust-policy-continuous-integration:
    uses: jvanz/github-actions/.github/workflows/reusable-test-policy-rust.yml@monorepo
    if: ${{ needs.calculate-policy-matrix.outputs.policy_rust_working_dirs != '[]' }}
    needs: calculate-policy-matrix
    strategy:
      matrix:
        policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_rust_working_dirs) }}
    with:
      policy-working-dir: ${{ matrix.policy-working-dir }}

  build-all-rust-policies:
    if: ${{ needs.calculate-policy-matrix.outputs.policy_rust_working_dirs == '[]' && needs.calculate-policy-matrix.outputs.global_cargo_file_change == 'true' }}
    needs: calculate-policy-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # checkout all history to do git diff
      - name: Build all policies
        shell: bash
        run: |
          pushd policies
          cargo build --all --workspace

  go-policy-continuous-integration:
    runs-on: ubuntu-latest
    if: ${{ needs.calculate-policy-matrix.outputs.policy_go_working_dirs != '[]' }}
    needs: calculate-policy-matrix
    strategy:
      matrix:
        policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_go_working_dirs) }}
    steps:
      - name: Testing step
        shell: bash
        run: echo "Testing step"
