# This GitHub Actions workflow automates continuous integration for
# policy projects. It detects changes in the `policies/` directory on pull
# requests, determines which policies require CI jobs, and runs
# language-specific tests for Rust and Go policies using reusable workflows.
# The workflow calculates affected policy directories, distinguishes between
# Rust and Go projects, and triggers corresponding test jobs in parallel for
# each changed policy.
name: Continuous integration
on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  calculate-policy-matrix:
    runs-on: ubuntu-latest
    outputs:
      policy_working_dirs: ${{ steps.calculate-policy-dirs.outputs.policy_working_dirs }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # checkout all history to do git diff
      - name: calculate which policies need a CI job
        id: calculate-policy-dirs
        shell: bash
        run: |
          git remote -v
          # list only changes of files in `policies/`:
          git_files="$(git diff --no-color --find-renames --find-copies --name-only origin/${{ github.base_ref }} ${{ github.sha }} -- policies)"

          # build policy_working_dirs:
          dir_bash_array=($(echo "$git_files" | cut -d/ -f1,2,3 ))
          declare -p dir_bash_array # for debug
          policy_working_dirs=$(jq --compact-output --null-input '$ARGS.positional | map(select(. != "policies/rust/Cargo.lock" and . != "policies/rust/Cargo.toml")) | unique' --args -- "${dir_bash_array[@]}")
          echo "policy_working_dirs=$policy_working_dirs"
          echo "policy_working_dirs=$policy_working_dirs" >> $GITHUB_OUTPUT

  continuos-integration:
    uses: ./.github/workflows/reusable-ci.yaml
    needs: calculate-policy-matrix
    if: ${{ needs.calculate-policy-matrix.outputs.policy-working-dirs != '[]' }}
    strategy:
      matrix:
        policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_working_dirs) }}
    with:
      policy-working-dir: ${{ matrix.policy-working-dir }}
